spring:
  application:
    name: civicai-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/civicai_db
    username: postgres
    password: RishiAnan@7
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080